name: Build Physarum

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Download openFrameworks
      run: |
        git clone --depth 1 https://github.com/openframeworks/openFrameworks.git

    - name: Download addon
      run: |
        cd openFrameworks/addons
        git clone https://github.com/chrisspencer/ofxGamepad.git

    - name: Copy project
      run: |
        mkdir openFrameworks/apps/myApps
        xcopy interactive-physarum openFrameworks/apps/myApps/interactive-physarum /E /I

    - name: Build
      run: |
        cd openFrameworks/apps/myApps/interactive-physarum
        make Release

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: interactive-physarum
        path: openFrameworks/apps/myApps/interactive-physarum/bin
