name: Build Physarum

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Pobierz projekt
      uses: actions/checkout@v4

    - name: Pobierz openFrameworks
      run: |
        git clone --depth 1 https://github.com/openframeworks/openFrameworks.git

    - name: Skopiuj projekt do openFrameworks
      run: |
        mkdir openFrameworks/apps/myApps
        xcopy . openFrameworks/apps/myApps/interactive-physarum /E /I

    - name: Budowanie
      run: |
        cd openFrameworks/apps/myApps/interactive-physarum
        make Release

    - name: Spakuj wynik
      uses: actions/upload-artifact@v4
      with:
        name: interactive-physarum-build
        path: openFrameworks/apps/myApps/interactive-physarum/bin
