name: Build Physarum

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Pobierz openFrameworks
      run: |
        git clone --depth 1 https://github.com/openframeworks/openFrameworks.git

    - name: Pobierz projekt
      run: |
        git clone --depth 1 https://github.com/Bleuje/interactive-physarum.git openFrameworks/apps/myApps/interactive-physarum

    - name: Pobierz ofxGamepad
      run: |
        git clone --depth 1 https://github.com/Bleuje/ofxGamepad.git openFrameworks/addons/ofxGamepad

    - name: Budowanie
      run: |
        cd openFrameworks/apps/myApps/interactive-physarum
        make Release

    - name: Spakuj wynik
      uses: actions/upload-artifact@v4
      with:
        name: interactive-physarum-build
        path: openFrameworks/apps/myApps/interactive-physarum/bin
